(provide `cuda-cpp)
(setq CZQ-CUDA-CUBLAS-HANDLE-CODE "cublasHandle_t %s;\n    cublasCreate(&%s);\n    /*run cublas code form here using handle %s*/\n\n    cublasDestroy(%s);\n")
(setq CZQ-CUDA-CUBLAS-COPY-TO-DEVICE "%s* d_%s;\n    cudaMalloc(&d_%s,%s*sizeof(%s));\n    cublasSetVector(%s,sizeof(%s),%s,1,d_%s,1);\n    cublasGetVector(%s,sizeof(%s),d_%s,1,%s,1);\n    cudaFree(d_%s);")
(defun insert-cublasHandle-code-with-init-and-destroy (name)
  (interactive "svariable name:\n")
  (insert (format CZQ-CUDA-CUBLAS-HANDLE-CODE name name name name))
  (previous-line 2)
  )
(defun insert-cublasDeviceVariable-code-with-init-and-destroy (type name size)
  (interactive "stype:\nsname:\nssize:\n")
  (insert (format CZQ-CUDA-CUBLAS-COPY-TO-DEVICE type name name size type size type name name size type name name name))
  (previous-line 2)
  )
