(provide `czq-python)
(setq python-term-name "tpython")
(defun import-python-file ()
  (interactive)
  (setq current-python-file (file-name-base (buffer-name)))
  (run-in-python (format "import %s" current-python-file))
  )
(defun set-python-term-name (name)
  (interactive "st(name):")
  (setq python-term-name (format "t%s" name))
  (message python-term-name)
  )
(defun exec-selected-in-python (beginning end)
  (interactive "r")
  (if (use-region-p)   (setq python-command (buffer-substring beginning end)) 
    (setq python-command (thing-at-point `symbol))
      )
  (run-in-python python-command)
  )

(defun exec-selected-in-python-with-module (beginning end)
  (interactive "r")
  (setq python-current-module-name (file-name-base (buffer-name)))
  (if (use-region-p)   (setq python-command (buffer-substring beginning end)) 
    (setq python-command (thing-at-point `symbol))
      )
  (run-in-python (format "%s.%s" python-current-module-name python-command))
  )

(defun run-in-python (command)
  (interactive "scommand:")
  (save-window-excursion
    (progn
      (switch-to-buffer python-term-name)
      (term-send-raw-string (format "%s\n" command))
      )
    )
  )

(setq czq-python-function-pattern "def \\(.*\\):\n")
(defun exec-function-in-python ()
  (interactive )
  (save-excursion
    (progn
    (search-backward-regexp czq-python-function-pattern)
    (setq python-command (match-string 1))
    (setq python-current-module-name (file-name-base (buffer-name)))  
    (run-in-python (format "%s.%s" python-current-module-name python-command)))))

(defun  define-python-keys ()
  (interactive)
  (define-key python-mode-map (kbd "C-x C-e") `exec-selected-in-python-with-module)
  (define-key python-mode-map (kbd "C-x C-r") `exec-function-in-python)
  (define-key python-mode-map (kbd "C-c t") `set-python-term-name)
  (define-key python-mode-map (kbd "C-c i") `import-python-file)
  (define-key python-mode-map (kbd "C-c s") `czq-python-switch)
)


;;we extent it some common case
(defun czq-switch-to (old new)
  (interactive "sold:\nsnew")
  (setq czq-old-buffer-name (buffer-name))
  (setq czq-new-buffer-name (replace-regexp-in-string old new czq-old-buffer-name))
  (find-file czq-new-buffer-name)
  )
(defun czq-python-to-gene ()
  (interactive)
  (czq-switch-to "plot" "gene")
  )
(defun czq-python-to-plot ()
  (interactive)
  (czq-switch-to "gene" "plot")
  )

(defun czq-python-switch (target)
  (interactive "starget(p,g):")
  (cond
   ((string= target "p") (czq-python-to-plot))
   ((string= target "g") (czq-python-to-gene))
   ))
